---

- hosts: all
  become: true
  tasks:
  
  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: app_servers
  become: true
  tasks:
 
  - name: install apache and php for Ubuntu servers
    tags: Ubuntu,apache,php 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  

- hosts: file_servers
  become: true
  tasks:

  - name: install mariadb package on (CentOS)
    tags: CentOS,mariadb,samba
    yum:
      name: mariadb
    when: ansible_distribution == "CentOS"

    
  - name: install samba package
    package:
      name: samba
      state: latest

