- name: install apache and php for Ubuntu servers
  apt:
   name: installing apache2
     - apache2
   state: latest
  when: ansible_distribution == "Ubuntu"


- name: copy default html file for site
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
